package com.glitch.securenotes.data.exceptions.auth

class LoginAlreadyInUseException(): Throwable("This login is already in use")